[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cruise-lang"
version = "0.4.3"
authors = [
  { name = "Manjas Anand", email = "manjasanand08@gmail.com" }
]
description = "Cruise: An AI-ready, lightweight programming language with native file system (fs), PyTorch tensors, AST parser, CPM, and GUI framework."
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.8"
keywords = [
  "cruise-lang",
  "cruise",
  "programming-language",
  "interpreter",
  "ast-parser",
  "pytorch-tensors",
  "file-system",
  "cpm-package-manager",
  "deep-learning"
]
dependencies = [
    "torch",
    "numpy",
    "requests"
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Topic :: Software Development :: Interpreters",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://manjas-developer.github.io/Cruise-Website/"
Repository = "https://github.com/manjas-developer/Cruise"
Documentation = "https://manjas-developer.github.io/Cruise-Website/"
"Bug Tracker" = "https://github.com/manjas-developer/Cruise/issues"
"Indian Users Support Here" = "https://buymeachai.in/manjasanand08"
"International Users Support Here" = "https://throne.com/manjas-developer/item/d83a6389-fc12-4d64-a4e1-cf4dc4d1dc45"

[project.scripts]
cruise = "cruise:main"

[tool.setuptools]
py-modules = ["cruise"]
