[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cruise-lang"
version = "0.1.1"
authors = [
  { name = "Manjas Anand" }
]
description = "Cruise: An AI-powered, tensor-ready lightweight programming language interpreter."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "torch",
    "scikit-learn",
    "numpy"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.scripts]
cruise = "main:main"

[tool.setuptools]
py-modules = ["main"]
